### ISSUE TITLE
Error with space in path

### ISSUE THREAD

**Issue by KibosJ** [luckman212/bw-cache-update#1]
My Alfred settings are stored in a path with a space and special character (iCloud) and I get an error when trying to run the script

`found workflow v2.2.2 at /Users/james/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CCA210CF-B304-415E-A256-549C64D8C8E7
/usr/local/bin/bw_cache_update.sh: line 45: /Users/james/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CCA210CF-B304-415E-A256-549C64D8C8E7/bitwarden-alfred-workflow: No such file or directory
`

**Comment by luckman212** [comment]
@KibosJ I really slipped with submitting my PR to the main project. I have an updated version of the script ready, I'll test to confirm it works with paths such as yours and try to push an update today.
